name: Deploys the helm-chart from provided values
on:
  workflow_call:
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true
      K8S_CLUSTER:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve helm-template
        uses: actions/checkout@v3
        with:
          repository: SolidsquareAS/helm-templates
          token: ${{ secrets.GH_PAT }}
          ref: master
          path: helm-templates
      - name: get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.K8S_CLUSTER }}
      - name: Install helm
        uses: azure/setup-helm@v3
      - name: Deploy
        run: helm upgrade ${{ env.REPOSITORY_NAME }} ./helm-template/helm --dry-run
