name: Echo file

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve helm-template
        uses: actions/checkout@v3
        with:
          repository: SolidsquareAS/helm-templates
          token: ${{ secrets.GH_PAT }}
          ref: master
      - name: print directory
        run: ls
      - name: print file
        run: cat ./index.html
