name: Echo file

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: source
      - name: Retrieve helm-templates
        uses: actions/checkout@v3
        with:
          repository: SolidsquareAS/helm-templates
          token: ${{ secrets.GH_PAT }}
          ref: master
          path: helm-templates
      - name: print directory
        run: ls
      - name: print directory
        run: ls ./helm-templates
